// data.js
export const products = [
    {
        id: '51',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/cafe-latte--flat-white--white-mocha-cortado--32-32.png',
        name: 'Caffe Latte',
        price: '65 TL',
      },
      {
        id: '52',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/cappuccino---32--7-11zon1.png',
        name: 'Cappuccino',
        price: '75 TL',
      },
      {
        id: '53',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/americano--2-32.png',
        name: 'Americano',
        price: '65 TL',
      },
      {
        id: '54',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/espresso-macchiato1.png',
        name: 'Espresso Macchiato',
        price: '45 TL',
      },
      {
        id: '55',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/cafe-latte--flat-white--white-mocha-cortado--2-3.png',
        name: 'Flat White',
        price: '40 TL',
      },
      {
        id: '56',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/espresso-single-9-11zon-11zon1.png',
        name: 'Espresso Single',
        price: '40 TL',
      },
      {
        id: '57',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/filtre-kahve1.png',
        name: 'Filtre Kahve',
        price: '40 TL',
      },
      {
        id: '58',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/sutlu-filtre-kahve1.png',
        name: 'Sütlü Filtre Kahve',
        price: '40 TL',
      },
      {
        id: '59',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/red--black--dead-eye3.png',
        name: 'Red Eye',
        price: '40 TL',
      },
      {
        id: '60',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/cafe-latte--flat-white--white-mocha-cortado--2-11.png',
        name: 'Cortado',
        price: '40 TL',
      },
      {
        id: '61',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/baby-coco1.png',
        name: 'Baby Coco',
        price: '65 TL',
      },
      {
        id: '62',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/ruby-chocolate-soguk1.png',
        name: 'Ruby Chocolate',
        price: '75 TL',
      },
      {
        id: '63',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/cilek-cooler.png',
        name: 'Çilekli Fruities',
        price: '65 TL',
      },
      {
        id: '64',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/kavun-ananas-cooler1.png',
        name: 'Kavun Ananas Fruities',
        price: '45 TL',
      },
      {
        id: '65',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/limonata1.png',
        name: 'Limonata',
        price: '40 TL',
      },
      {
        id: '66',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/cilekli-limonata.png',
        name: 'Çilekli Limonata',
        price: '40 TL',
      },
      {
        id: '67',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/kirmizi-orman-meyveli-cooler1.png',
        name: 'Kırmızı Orman Meyveli Fruities',
        price: '40 TL',
      },
      {
        id: '68',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/mango-cooler1.png',
        name: 'Mangolu Fruities',
        price: '40 TL',
      },
      {
        id: '69',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/turk-kahvesi-single1.png',
        name: 'Türk Kahvesi',
        price: '65 TL',
      },
      {
        id: '70',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/turk-kahvesi-double1.png',
        name: 'Türk Kahvesi Double',
        price: '75 TL',
      },
      {
        id: '71',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/dibek-kahvesi-single1.png',
        name: 'Dibek Kahvesi',
        price: '65 TL',
      },
      {
        id: '72',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/dibek-kahvesi-double1.png',
        name: 'Dibek Kahvesi Double',
        price: '45 TL',
      },
      {
        id: '73',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/soguk-filtre-kahve--32-1.png',
        name: 'Ice Filter Coffee',
        price: '65 TL',
      },
      {
        id: '74',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/soguk-sutlu-filtre-kahve1.png',
        name: 'Ice Filter Coffee with Milk',
        price: '75 TL',
      },
    {
      id: '75',
      image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/1png2.png',
      name: 'Ice Caffe Latte',
      price: '75 TL',
    },
    
    {
      id: '76',
      image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/soguk-filtre-kahve--3-1.png',
      name: 'Ice Americano',
      price: '75 TL',
    },
    {
      id: '77',
      image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/ice-americano---ice-red-black-dead-eye3.png',
      name: 'Ice Black Eye',
      price: '75 TL',
    },
    {
      id: '78',
      image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/ice-cortado1.png',
      name: 'Ice Cortado',
      price: '75 TL',
    },
    {
      id: '79',
      image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/soguk-sutlu-filtre-kahve1.png',
      name: 'Ice Filter Coffee with Milk',
      price: '75 TL',
    },
    {
      id: '80',
      image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/1png.png',
      name: 'Ice Flat White',
      price: '75 TL',
    },
    {
      id: '81',
      image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/ice-americano---ice-red-black-dead-eye11.png',
      name: 'Buzlu Dead Eye',
      price: '75 TL',
    },
    {
        id: '82',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/limonlu-cheesecake1.png',
       name: 'Limonlu Cheesecake',
        price: '65 TL',
      },
      {
        id: '83',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/mosaik-pasta1.png',
       name: 'Mozaik Pasta',
        price: '75 TL',
      },
      {
        id: '84',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/red-velvet1.png',
       name: 'Red Velvet',
        price: '65 TL',
      },
      {
        id: '85',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/tiramisu1.png',
       name: 'Tiramisu',
        price: '45 TL',
      },
      {
        id: '86',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/41.png',
       name: 'Purple Velvet',
        price: '40 TL',
      },
      {
        id: '87',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/san-sebastian-kucuk.png',
       name: 'Cheesecake San Sebastian',
        price: '40 TL',
      },
      {
        id: '88',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/19-kucuk.png',
       name: 'Cookie Dark Chocolate',
        price: '40 TL',
      },
      {
        id: '89',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/18-kucuk.png',
       name: ' Cookie Drop',
        price: '40 TL',
      },
      {
        id: '90',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/17911d2a-b845-44d0-bf03-e5a5b2e6058a.jpg',
       name: 'Beyaz Çikolatalı Brownie',
        price: '40 TL',
      },
      {
        id: '91',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/karamelli-cheesecake-kucuk.png',
       name: 'Cheesecake Karamelli Fıstıklı',
        price: '40 TL',
      },

      {
        id: '92',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/demleme-cay1.png',
        name: 'Demleme Çay',
        price: '65 TL',
      },
      {
        id: '93',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/balli-zencefilli-cay1.png',
        name: 'Ballı Zencefilli Çay',
        price: '75 TL',
      },
      {
        id: '94',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/earl-grey1.png',
        name: 'Earl Grey',
        price: '65 TL',
      },
      {
        id: '95',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/kis-cayi11.png',
        name: 'Kış Çayı',
        price: '45 TL',
      },
      {
        id: '96',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/relax-cay1.png',
        name: 'Relax Çay',
        price: '40 TL',
      },
      {
        id: '97',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/yesil-cay--detox--bora-bora3.png',
        name: 'Yeşil Çay',
        price: '40 TL',
      },
      {
        id: '98',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/yesil-cay--detox--bora-bora11.png',
        name: 'Detox Çay',
        price: '40 TL',
      },
      {
        id: '99',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/yesil-cay--detox--bora-bora21.png',
        name: ' Bora Bora',
        price: '40 TL',
      },
      {
        id: '100',
        image: 'https://arabicacoffee.com.tr/Uploads/urunler_view/kirmizi-orman.png',
        name: 'Kırmızı Orman',
        price: '40 TL',
      },
   
  ];
  